// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myAPI.DataAccessLayer.Contexts;

#nullable disable

namespace myAPI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220805124238_nested_test")]
    partial class nested_test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExperienceExperienceProject", b =>
                {
                    b.Property<int>("ExperienceProjectsID")
                        .HasColumnType("int");

                    b.Property<int>("ExperiencesExperienceID")
                        .HasColumnType("int");

                    b.HasKey("ExperienceProjectsID", "ExperiencesExperienceID");

                    b.HasIndex("ExperiencesExperienceID");

                    b.ToTable("ExperienceExperienceProject");
                });

            modelBuilder.Entity("ExperienceExperienceResponsibility", b =>
                {
                    b.Property<int>("ExperienceResponsibilitiesID")
                        .HasColumnType("int");

                    b.Property<int>("ExperiencesExperienceID")
                        .HasColumnType("int");

                    b.HasKey("ExperienceResponsibilitiesID", "ExperiencesExperienceID");

                    b.HasIndex("ExperiencesExperienceID");

                    b.ToTable("ExperienceExperienceResponsibility");
                });

            modelBuilder.Entity("myAPI.EntityLayer.Concrete.Experience", b =>
                {
                    b.Property<int>("ExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("ExperienceID");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("myAPI.EntityLayer.Concrete.ExperienceProject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceID")
                        .HasColumnType("int");

                    b.Property<string>("Project")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("ExperienceProjects");
                });

            modelBuilder.Entity("myAPI.EntityLayer.Concrete.ExperienceResponsibility", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ExperienceID")
                        .HasColumnType("int");

                    b.Property<string>("Responsibility")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("ExperienceResponsibilities");
                });

            modelBuilder.Entity("myAPI.EntityLayer.Concrete.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Detail")
                        .HasColumnType("longtext");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ExperienceExperienceProject", b =>
                {
                    b.HasOne("myAPI.EntityLayer.Concrete.ExperienceProject", null)
                        .WithMany()
                        .HasForeignKey("ExperienceProjectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myAPI.EntityLayer.Concrete.Experience", null)
                        .WithMany()
                        .HasForeignKey("ExperiencesExperienceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExperienceExperienceResponsibility", b =>
                {
                    b.HasOne("myAPI.EntityLayer.Concrete.ExperienceResponsibility", null)
                        .WithMany()
                        .HasForeignKey("ExperienceResponsibilitiesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myAPI.EntityLayer.Concrete.Experience", null)
                        .WithMany()
                        .HasForeignKey("ExperiencesExperienceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
